-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fe_wfl is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    sampleFifo_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    sampleFifo_V_V_empty_n : IN STD_LOGIC;
    sampleFifo_V_V_read : OUT STD_LOGIC;
    featureFifo_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    featureFifo_V_V_full_n : IN STD_LOGIC;
    featureFifo_V_V_write : OUT STD_LOGIC;
    windowSize_V : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of fe_wfl is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fe_wfl,hls_ip_2016_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.730000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=271,HLS_SYN_LUT=378}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";

    signal sampleFifo_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_29 : BOOLEAN;
    signal tmp_1_fu_113_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal featureFifo_V_V_blk_n : STD_LOGIC;
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_43 : BOOLEAN;
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_53 : BOOLEAN;
    signal tmp_1_reg_302 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_61 : BOOLEAN;
    signal tmp_V_load_reg_306 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_V_1_load_reg_313 : STD_LOGIC_VECTOR (31 downto 0);
    signal sampleChannel1_V_fu_125_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sampleChannel1_V_reg_319 : STD_LOGIC_VECTOR (15 downto 0);
    signal sampleChannel2_V_reg_325 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_331 : STD_LOGIC_VECTOR (0 downto 0);
    signal wflChannel1_V_1_fu_234_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal wflChannel1_V_1_reg_337 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_3 : STD_LOGIC;
    signal ap_sig_82 : BOOLEAN;
    signal wflChannel2_V_1_fu_240_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal wflChannel2_V_1_reg_342 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_V_fu_46 : STD_LOGIC_VECTOR (7 downto 0);
    signal cntSamples_V_fu_145_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_V_fu_50 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st5_fsm_4 : STD_LOGIC;
    signal ap_sig_105 : BOOLEAN;
    signal tmp_V_1_fu_54 : STD_LOGIC_VECTOR (31 downto 0);
    signal prevSampleChannel2_V_fu_58 : STD_LOGIC_VECTOR (15 downto 0);
    signal prevSampleChannel1_V_fu_62 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_162_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_167_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_175_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge_fu_181_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_189_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_198_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_203_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_211_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge1_fu_217_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_225_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal wflChannel1_V_fu_193_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal wflChannel2_V_fu_229_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    prevSampleChannel1_V_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then 
                prevSampleChannel1_V_fu_62 <= sampleChannel1_V_reg_319;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) then 
                prevSampleChannel1_V_fu_62 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    prevSampleChannel2_V_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then 
                prevSampleChannel2_V_fu_58 <= sampleChannel2_V_reg_325;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) then 
                prevSampleChannel2_V_fu_58 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    t_V_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((tmp_1_fu_113_p2 = ap_const_lv1_0)) and not(ap_sig_61))) then 
                t_V_fu_46 <= cntSamples_V_fu_145_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (tmp_1_fu_113_p2 = ap_const_lv1_0) and not(ap_sig_61)))) then 
                t_V_fu_46 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    tmp_V_1_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = tmp_1_reg_302)))) then 
                tmp_V_1_fu_54 <= wflChannel1_V_1_reg_337;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (tmp_1_fu_113_p2 = ap_const_lv1_0) and not(ap_sig_61)))) then 
                tmp_V_1_fu_54 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    tmp_V_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = tmp_1_reg_302)))) then 
                tmp_V_fu_50 <= wflChannel2_V_1_reg_342;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (tmp_1_fu_113_p2 = ap_const_lv1_0) and not(ap_sig_61)))) then 
                tmp_V_fu_50 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((tmp_1_fu_113_p2 = ap_const_lv1_0)) and not(ap_sig_61))) then
                sampleChannel1_V_reg_319 <= sampleChannel1_V_fu_125_p1;
                sampleChannel2_V_reg_325 <= sampleFifo_V_V_dout(31 downto 16);
                tmp_3_reg_331 <= tmp_3_fu_139_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not(ap_sig_61))) then
                tmp_1_reg_302 <= tmp_1_fu_113_p2;
                tmp_V_1_load_reg_313 <= tmp_V_1_fu_54;
                tmp_V_load_reg_306 <= tmp_V_fu_50;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then
                wflChannel1_V_1_reg_337 <= wflChannel1_V_1_fu_234_p3;
                wflChannel2_V_1_reg_342 <= wflChannel2_V_1_fu_240_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (featureFifo_V_V_full_n, ap_CS_fsm, tmp_1_fu_113_p2, ap_sig_61)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                ap_NS_fsm <= ap_ST_st2_fsm_1;
            when ap_ST_st2_fsm_1 => 
                if ((not((tmp_1_fu_113_p2 = ap_const_lv1_0)) and not(ap_sig_61))) then
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                elsif (((tmp_1_fu_113_p2 = ap_const_lv1_0) and not(ap_sig_61))) then
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                end if;
            when ap_ST_st3_fsm_2 => 
                if (not((featureFifo_V_V_full_n = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_st5_fsm_4;
                else
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                end if;
            when ap_ST_st4_fsm_3 => 
                ap_NS_fsm <= ap_ST_st5_fsm_4;
            when ap_ST_st5_fsm_4 => 
                ap_NS_fsm <= ap_ST_st2_fsm_1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;

    ap_sig_105_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_105 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    ap_sig_29_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_29 <= (ap_CS_fsm(1 downto 1) = ap_const_lv1_1);
    end process;


    ap_sig_43_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_43 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    ap_sig_53_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_53 <= (ap_const_lv1_1 = ap_CS_fsm(0 downto 0));
    end process;


    ap_sig_61_assign_proc : process(sampleFifo_V_V_empty_n, featureFifo_V_V_full_n, tmp_1_fu_113_p2)
    begin
                ap_sig_61 <= (((tmp_1_fu_113_p2 = ap_const_lv1_0) and (featureFifo_V_V_full_n = ap_const_logic_0)) or (not((tmp_1_fu_113_p2 = ap_const_lv1_0)) and (sampleFifo_V_V_empty_n = ap_const_logic_0)));
    end process;


    ap_sig_82_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_82 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_53)
    begin
        if (ap_sig_53) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_29)
    begin
        if (ap_sig_29) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_43)
    begin
        if (ap_sig_43) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st4_fsm_3_assign_proc : process(ap_sig_82)
    begin
        if (ap_sig_82) then 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st5_fsm_4_assign_proc : process(ap_sig_105)
    begin
        if (ap_sig_105) then 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;

    cntSamples_V_fu_145_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(t_V_fu_46));

    featureFifo_V_V_blk_n_assign_proc : process(featureFifo_V_V_full_n, ap_sig_cseq_ST_st2_fsm_1, tmp_1_fu_113_p2, ap_sig_cseq_ST_st3_fsm_2)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (tmp_1_fu_113_p2 = ap_const_lv1_0)) or (ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2))) then 
            featureFifo_V_V_blk_n <= featureFifo_V_V_full_n;
        else 
            featureFifo_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    featureFifo_V_V_din_assign_proc : process(featureFifo_V_V_full_n, ap_sig_cseq_ST_st2_fsm_1, tmp_1_fu_113_p2, ap_sig_cseq_ST_st3_fsm_2, ap_sig_61, tmp_V_load_reg_306, tmp_V_1_fu_54)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((featureFifo_V_V_full_n = ap_const_logic_0)))) then 
            featureFifo_V_V_din <= tmp_V_load_reg_306;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (tmp_1_fu_113_p2 = ap_const_lv1_0) and not(ap_sig_61))) then 
            featureFifo_V_V_din <= tmp_V_1_fu_54;
        else 
            featureFifo_V_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    featureFifo_V_V_write_assign_proc : process(featureFifo_V_V_full_n, ap_sig_cseq_ST_st2_fsm_1, tmp_1_fu_113_p2, ap_sig_cseq_ST_st3_fsm_2, ap_sig_61)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (tmp_1_fu_113_p2 = ap_const_lv1_0) and not(ap_sig_61)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((featureFifo_V_V_full_n = ap_const_logic_0))))) then 
            featureFifo_V_V_write <= ap_const_logic_1;
        else 
            featureFifo_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    sampleChannel1_V_fu_125_p1 <= sampleFifo_V_V_dout(16 - 1 downto 0);

    sampleFifo_V_V_blk_n_assign_proc : process(sampleFifo_V_V_empty_n, ap_sig_cseq_ST_st2_fsm_1, tmp_1_fu_113_p2)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((tmp_1_fu_113_p2 = ap_const_lv1_0)))) then 
            sampleFifo_V_V_blk_n <= sampleFifo_V_V_empty_n;
        else 
            sampleFifo_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    sampleFifo_V_V_read_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, tmp_1_fu_113_p2, ap_sig_61)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((tmp_1_fu_113_p2 = ap_const_lv1_0)) and not(ap_sig_61))) then 
            sampleFifo_V_V_read <= ap_const_logic_1;
        else 
            sampleFifo_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    storemerge1_fu_217_p3 <= 
        tmp_4_fu_211_p2 when (tmp_2_fu_203_p3(0) = '1') else 
        tmp_s_fu_198_p2;
    storemerge_fu_181_p3 <= 
        tmp_8_fu_175_p2 when (tmp_fu_167_p3(0) = '1') else 
        tmp_6_fu_162_p2;
    tmp_1_fu_113_p2 <= "1" when (unsigned(t_V_fu_46) < unsigned(windowSize_V)) else "0";
    tmp_2_fu_203_p3 <= tmp_s_fu_198_p2(15 downto 15);
    tmp_3_fu_139_p2 <= "1" when (t_V_fu_46 = ap_const_lv8_0) else "0";
    tmp_4_fu_211_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(tmp_s_fu_198_p2));
        tmp_5_fu_225_p1 <= std_logic_vector(resize(signed(storemerge1_fu_217_p3),32));

    tmp_6_fu_162_p2 <= std_logic_vector(unsigned(sampleChannel1_V_reg_319) - unsigned(prevSampleChannel1_V_fu_62));
    tmp_8_fu_175_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(tmp_6_fu_162_p2));
        tmp_9_fu_189_p1 <= std_logic_vector(resize(signed(storemerge_fu_181_p3),32));

    tmp_fu_167_p3 <= tmp_6_fu_162_p2(15 downto 15);
    tmp_s_fu_198_p2 <= std_logic_vector(unsigned(sampleChannel2_V_reg_325) - unsigned(prevSampleChannel2_V_fu_58));
    wflChannel1_V_1_fu_234_p3 <= 
        tmp_V_1_load_reg_313 when (tmp_3_reg_331(0) = '1') else 
        wflChannel1_V_fu_193_p2;
    wflChannel1_V_fu_193_p2 <= std_logic_vector(signed(tmp_9_fu_189_p1) + signed(tmp_V_1_load_reg_313));
    wflChannel2_V_1_fu_240_p3 <= 
        tmp_V_load_reg_306 when (tmp_3_reg_331(0) = '1') else 
        wflChannel2_V_fu_229_p2;
    wflChannel2_V_fu_229_p2 <= std_logic_vector(signed(tmp_5_fu_225_p1) + signed(tmp_V_load_reg_306));
end behav;
