-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fe_zc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    sampleFifo_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    sampleFifo_V_V_empty_n : IN STD_LOGIC;
    sampleFifo_V_V_read : OUT STD_LOGIC;
    featureFifo_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    featureFifo_V_V_full_n : IN STD_LOGIC;
    featureFifo_V_V_write : OUT STD_LOGIC;
    windowSize_V : IN STD_LOGIC_VECTOR (7 downto 0);
    threshold_V : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of fe_zc is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fe_zc,hls_ip_2016_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.132000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=160,HLS_SYN_LUT=627}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_st6_fsm_5 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";

    signal sampleFifo_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_31 : BOOLEAN;
    signal exitcond_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal featureFifo_V_V_blk_n : STD_LOGIC;
    signal ap_sig_cseq_ST_st6_fsm_5 : STD_LOGIC;
    signal ap_sig_45 : BOOLEAN;
    signal cntSamples_V_fu_155_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal cntSamples_V_reg_577 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_66 : BOOLEAN;
    signal tmp_V_reg_582 : STD_LOGIC_VECTOR (31 downto 0);
    signal sampleChannel1_V_fu_161_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sampleChannel1_V_reg_588 : STD_LOGIC_VECTOR (15 downto 0);
    signal sampleChannel2_V_reg_595 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_10_reg_602 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_3 : STD_LOGIC;
    signal ap_sig_83 : BOOLEAN;
    signal not_tmp_s_fu_253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_s_reg_609 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_614 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_reg_619 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_1_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_1_reg_626 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_631 : STD_LOGIC_VECTOR (0 downto 0);
    signal zcChannel1_V_4_fu_373_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st5_fsm_4 : STD_LOGIC;
    signal ap_sig_102 : BOOLEAN;
    signal p_0373_s_fu_416_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zcChannel2_V_4_fu_512_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0401_s_fu_555_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal t_V_6_reg_89 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_117 : BOOLEAN;
    signal t_V_5_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_s_reg_115 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_1_reg_127 : STD_LOGIC_VECTOR (1 downto 0);
    signal t_V_reg_139 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_175_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_182_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sampleChannel1_V_1_fu_187_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_194_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_210_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_217_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sampleChannel2_V_2_fu_222_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_229_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_6_fu_203_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sampleChannel2_V_1_fu_238_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zcChannel1_V_fu_313_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_291_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zcChannel1_V_2_fu_352_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_1_7_fu_319_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zcChannel1_V_3_fu_365_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0373_1_cast_fu_299_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp2_fu_392_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp4_fu_400_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_2_fu_327_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp6_fu_408_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_16_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_fu_447_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zcChannel2_V_fu_452_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_430_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zcChannel2_V_2_fu_491_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_3_fu_458_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zcChannel2_V_3_fu_504_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp11_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_fu_525_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0401_1_cast_fu_438_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp13_fu_531_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp14_fu_539_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_4_fu_466_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp15_fu_547_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    p_1_reg_127_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then 
                p_1_reg_127 <= p_0401_s_fu_555_p3;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                p_1_reg_127 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    p_s_reg_115_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then 
                p_s_reg_115 <= p_0373_s_fu_416_p3;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                p_s_reg_115 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    t_V_5_reg_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then 
                t_V_5_reg_102 <= zcChannel2_V_4_fu_512_p3;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                t_V_5_reg_102 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    t_V_6_reg_89_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then 
                t_V_6_reg_89 <= zcChannel1_V_4_fu_373_p3;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                t_V_6_reg_89 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    t_V_reg_139_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then 
                t_V_reg_139 <= cntSamples_V_reg_577;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                t_V_reg_139 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not(ap_sig_66))) then
                cntSamples_V_reg_577 <= cntSamples_V_fu_155_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then
                not_tmp_1_reg_626 <= not_tmp_1_fu_273_p2;
                not_tmp_s_reg_609 <= not_tmp_s_fu_253_p2;
                tmp_10_reg_602 <= p_s_6_fu_203_p3(15 downto 15);
                tmp_13_reg_631 <= tmp_13_fu_279_p2;
                tmp_15_reg_619 <= sampleChannel2_V_1_fu_238_p3(15 downto 15);
                tmp_3_reg_614 <= tmp_3_fu_259_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (exitcond_fu_150_p2 = ap_const_lv1_0) and not(ap_sig_66))) then
                sampleChannel1_V_reg_588 <= sampleChannel1_V_fu_161_p1;
                sampleChannel2_V_reg_595 <= sampleFifo_V_V_dout(31 downto 16);
                tmp_V_reg_582 <= sampleFifo_V_V_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (featureFifo_V_V_full_n, ap_CS_fsm, exitcond_fu_150_p2, ap_sig_66)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                ap_NS_fsm <= ap_ST_st2_fsm_1;
            when ap_ST_st2_fsm_1 => 
                ap_NS_fsm <= ap_ST_st3_fsm_2;
            when ap_ST_st3_fsm_2 => 
                if ((not((exitcond_fu_150_p2 = ap_const_lv1_0)) and not(ap_sig_66))) then
                    ap_NS_fsm <= ap_ST_st6_fsm_5;
                elsif (((exitcond_fu_150_p2 = ap_const_lv1_0) and not(ap_sig_66))) then
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                else
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                end if;
            when ap_ST_st4_fsm_3 => 
                ap_NS_fsm <= ap_ST_st5_fsm_4;
            when ap_ST_st5_fsm_4 => 
                ap_NS_fsm <= ap_ST_st3_fsm_2;
            when ap_ST_st6_fsm_5 => 
                if (not((featureFifo_V_V_full_n = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st6_fsm_5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    ap_sig_102_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_102 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    ap_sig_117_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_117 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_31_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_31 <= (ap_CS_fsm(2 downto 2) = ap_const_lv1_1);
    end process;


    ap_sig_45_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_45 <= (ap_const_lv1_1 = ap_CS_fsm(5 downto 5));
    end process;


    ap_sig_66_assign_proc : process(sampleFifo_V_V_empty_n, featureFifo_V_V_full_n, exitcond_fu_150_p2)
    begin
                ap_sig_66 <= (((exitcond_fu_150_p2 = ap_const_lv1_0) and (sampleFifo_V_V_empty_n = ap_const_logic_0)) or (not((exitcond_fu_150_p2 = ap_const_lv1_0)) and (featureFifo_V_V_full_n = ap_const_logic_0)));
    end process;


    ap_sig_83_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_83 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_117)
    begin
        if (ap_sig_117) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_31)
    begin
        if (ap_sig_31) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st4_fsm_3_assign_proc : process(ap_sig_83)
    begin
        if (ap_sig_83) then 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st5_fsm_4_assign_proc : process(ap_sig_102)
    begin
        if (ap_sig_102) then 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st6_fsm_5_assign_proc : process(ap_sig_45)
    begin
        if (ap_sig_45) then 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_0;
        end if; 
    end process;

    cntSamples_V_fu_155_p2 <= std_logic_vector(unsigned(t_V_reg_139) + unsigned(ap_const_lv8_1));
    exitcond_fu_150_p2 <= "1" when (t_V_reg_139 = windowSize_V) else "0";

    featureFifo_V_V_blk_n_assign_proc : process(featureFifo_V_V_full_n, ap_sig_cseq_ST_st3_fsm_2, exitcond_fu_150_p2, ap_sig_cseq_ST_st6_fsm_5)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((exitcond_fu_150_p2 = ap_const_lv1_0))) or (ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5))) then 
            featureFifo_V_V_blk_n <= featureFifo_V_V_full_n;
        else 
            featureFifo_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    featureFifo_V_V_din_assign_proc : process(featureFifo_V_V_full_n, ap_sig_cseq_ST_st3_fsm_2, exitcond_fu_150_p2, ap_sig_cseq_ST_st6_fsm_5, ap_sig_66, t_V_6_reg_89, t_V_5_reg_102)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5) and not((featureFifo_V_V_full_n = ap_const_logic_0)))) then 
            featureFifo_V_V_din <= t_V_5_reg_102;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((exitcond_fu_150_p2 = ap_const_lv1_0)) and not(ap_sig_66))) then 
            featureFifo_V_V_din <= t_V_6_reg_89;
        else 
            featureFifo_V_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    featureFifo_V_V_write_assign_proc : process(featureFifo_V_V_full_n, ap_sig_cseq_ST_st3_fsm_2, exitcond_fu_150_p2, ap_sig_cseq_ST_st6_fsm_5, ap_sig_66)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((exitcond_fu_150_p2 = ap_const_lv1_0)) and not(ap_sig_66)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5) and not((featureFifo_V_V_full_n = ap_const_logic_0))))) then 
            featureFifo_V_V_write <= ap_const_logic_1;
        else 
            featureFifo_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    not_tmp_1_fu_273_p2 <= "0" when (sampleChannel2_V_1_fu_238_p3 = ap_const_lv16_0) else "1";
    not_tmp_s_fu_253_p2 <= "0" when (p_s_6_fu_203_p3 = ap_const_lv16_0) else "1";
    or_cond1_fu_447_p2 <= (tmp_16_fu_441_p2 and tmp_15_reg_619);
    or_cond_fu_308_p2 <= (tmp_11_fu_302_p2 and tmp_10_reg_602);
    p_0373_1_cast_fu_299_p1 <= std_logic_vector(resize(unsigned(not_tmp_s_reg_609),2));
    p_0373_s_fu_416_p3 <= 
        p_2_fu_327_p3 when (tmp_11_fu_302_p2(0) = '1') else 
        sel_tmp6_fu_408_p3;
    p_0401_1_cast_fu_438_p1 <= std_logic_vector(resize(unsigned(not_tmp_1_reg_626),2));
    p_0401_s_fu_555_p3 <= 
        p_4_fu_466_p3 when (tmp_16_fu_441_p2(0) = '1') else 
        sel_tmp15_fu_547_p3;
    p_1_7_fu_319_p3 <= 
        zcChannel1_V_fu_313_p2 when (or_cond_fu_308_p2(0) = '1') else 
        t_V_6_reg_89;
    p_2_fu_327_p3 <= 
        ap_const_lv2_3 when (or_cond_fu_308_p2(0) = '1') else 
        p_s_reg_115;
    p_3_fu_458_p3 <= 
        zcChannel2_V_fu_452_p2 when (or_cond1_fu_447_p2(0) = '1') else 
        t_V_5_reg_102;
    p_4_fu_466_p3 <= 
        ap_const_lv2_3 when (or_cond1_fu_447_p2(0) = '1') else 
        p_1_reg_127;
    p_s_6_fu_203_p3 <= 
        ap_const_lv16_0 when (tmp_7_fu_198_p2(0) = '1') else 
        sampleChannel1_V_reg_588;
    sampleChannel1_V_1_fu_187_p3 <= 
        tmp_5_fu_182_p2 when (tmp_4_fu_175_p3(0) = '1') else 
        sampleChannel1_V_reg_588;
    sampleChannel1_V_fu_161_p1 <= sampleFifo_V_V_dout(16 - 1 downto 0);
    sampleChannel2_V_1_fu_238_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_233_p2(0) = '1') else 
        sampleChannel2_V_reg_595;
    sampleChannel2_V_2_fu_222_p3 <= 
        tmp_9_fu_217_p2 when (tmp_8_fu_210_p3(0) = '1') else 
        sampleChannel2_V_reg_595;

    sampleFifo_V_V_blk_n_assign_proc : process(sampleFifo_V_V_empty_n, ap_sig_cseq_ST_st3_fsm_2, exitcond_fu_150_p2)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (exitcond_fu_150_p2 = ap_const_lv1_0))) then 
            sampleFifo_V_V_blk_n <= sampleFifo_V_V_empty_n;
        else 
            sampleFifo_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    sampleFifo_V_V_read_assign_proc : process(ap_sig_cseq_ST_st3_fsm_2, exitcond_fu_150_p2, ap_sig_66)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (exitcond_fu_150_p2 = ap_const_lv1_0) and not(ap_sig_66))) then 
            sampleFifo_V_V_read <= ap_const_logic_1;
        else 
            sampleFifo_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    sel_tmp10_fu_499_p2 <= (tmp_12_fu_424_p2 and tmp_15_reg_619);
    sel_tmp11_fu_520_p2 <= (tmp_15_reg_619 xor ap_const_lv1_1);
    sel_tmp12_fu_525_p2 <= (tmp_12_fu_424_p2 and sel_tmp11_fu_520_p2);
    sel_tmp13_fu_531_p3 <= 
        p_0401_1_cast_fu_438_p1 when (sel_tmp12_fu_525_p2(0) = '1') else 
        p_1_reg_127;
    sel_tmp14_fu_539_p3 <= 
        p_0401_1_cast_fu_438_p1 when (sel_tmp9_fu_485_p2(0) = '1') else 
        sel_tmp13_fu_531_p3;
    sel_tmp15_fu_547_p3 <= 
        ap_const_lv2_3 when (sel_tmp10_fu_499_p2(0) = '1') else 
        sel_tmp14_fu_539_p3;
    sel_tmp1_fu_386_p2 <= (tmp_2_fu_285_p2 and sel_tmp_fu_381_p2);
    sel_tmp2_fu_392_p3 <= 
        p_0373_1_cast_fu_299_p1 when (sel_tmp1_fu_386_p2(0) = '1') else 
        p_s_reg_115;
    sel_tmp3_fu_335_p2 <= (tmp_2_fu_285_p2 xor ap_const_lv1_1);
    sel_tmp4_fu_400_p3 <= 
        p_0373_1_cast_fu_299_p1 when (sel_tmp5_fu_346_p2(0) = '1') else 
        sel_tmp2_fu_392_p3;
    sel_tmp5_fu_346_p2 <= (tmp_fu_341_p2 and tmp_14_fu_291_p3);
    sel_tmp6_fu_408_p3 <= 
        ap_const_lv2_3 when (sel_tmp7_fu_360_p2(0) = '1') else 
        sel_tmp4_fu_400_p3;
    sel_tmp7_fu_360_p2 <= (tmp_2_fu_285_p2 and tmp_10_reg_602);
    sel_tmp8_fu_474_p2 <= (tmp_12_fu_424_p2 xor ap_const_lv1_1);
    sel_tmp9_fu_485_p2 <= (tmp1_fu_480_p2 and tmp_18_fu_430_p3);
    sel_tmp_fu_381_p2 <= (tmp_10_reg_602 xor ap_const_lv1_1);
    tmp1_fu_480_p2 <= (tmp_13_reg_631 and sel_tmp8_fu_474_p2);
    tmp_11_fu_302_p2 <= "1" when (p_s_reg_115 = ap_const_lv2_1) else "0";
    tmp_12_fu_424_p2 <= "1" when (p_1_reg_127 = ap_const_lv2_0) else "0";
    tmp_13_fu_279_p2 <= "1" when (signed(sampleChannel2_V_1_fu_238_p3) > signed(ap_const_lv16_0)) else "0";
    tmp_14_fu_291_p3 <= p_s_reg_115(1 downto 1);
    tmp_16_fu_441_p2 <= "1" when (p_1_reg_127 = ap_const_lv2_1) else "0";
    tmp_18_fu_430_p3 <= p_1_reg_127(1 downto 1);
    tmp_1_fu_233_p2 <= "1" when (unsigned(tmp_s_fu_229_p1) < unsigned(threshold_V)) else "0";
    tmp_2_fu_285_p2 <= "1" when (p_s_reg_115 = ap_const_lv2_0) else "0";
    tmp_3_fu_259_p2 <= "1" when (signed(p_s_6_fu_203_p3) > signed(ap_const_lv16_0)) else "0";
    tmp_4_fu_175_p3 <= tmp_V_reg_582(15 downto 15);
    tmp_5_fu_182_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(sampleChannel1_V_reg_588));
        tmp_6_fu_194_p1 <= std_logic_vector(resize(signed(sampleChannel1_V_1_fu_187_p3),32));

    tmp_7_fu_198_p2 <= "1" when (unsigned(tmp_6_fu_194_p1) < unsigned(threshold_V)) else "0";
    tmp_8_fu_210_p3 <= tmp_V_reg_582(31 downto 31);
    tmp_9_fu_217_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(sampleChannel2_V_reg_595));
    tmp_fu_341_p2 <= (tmp_3_reg_614 and sel_tmp3_fu_335_p2);
        tmp_s_fu_229_p1 <= std_logic_vector(resize(signed(sampleChannel2_V_2_fu_222_p3),32));

    zcChannel1_V_2_fu_352_p3 <= 
        zcChannel1_V_fu_313_p2 when (sel_tmp5_fu_346_p2(0) = '1') else 
        t_V_6_reg_89;
    zcChannel1_V_3_fu_365_p3 <= 
        t_V_6_reg_89 when (sel_tmp7_fu_360_p2(0) = '1') else 
        zcChannel1_V_2_fu_352_p3;
    zcChannel1_V_4_fu_373_p3 <= 
        p_1_7_fu_319_p3 when (tmp_11_fu_302_p2(0) = '1') else 
        zcChannel1_V_3_fu_365_p3;
    zcChannel1_V_fu_313_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(t_V_6_reg_89));
    zcChannel2_V_2_fu_491_p3 <= 
        zcChannel2_V_fu_452_p2 when (sel_tmp9_fu_485_p2(0) = '1') else 
        t_V_5_reg_102;
    zcChannel2_V_3_fu_504_p3 <= 
        t_V_5_reg_102 when (sel_tmp10_fu_499_p2(0) = '1') else 
        zcChannel2_V_2_fu_491_p3;
    zcChannel2_V_4_fu_512_p3 <= 
        p_3_fu_458_p3 when (tmp_16_fu_441_p2(0) = '1') else 
        zcChannel2_V_3_fu_504_p3;
    zcChannel2_V_fu_452_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(t_V_5_reg_102));
end behav;
